<%@ Page AutoEventWireup="true" CodeBehind="kullanim_sartlari.aspx.cs" Inherits="GrafikerPortal.kullanim_sartlari" Language="C#" MasterPageFile="~/Main.Master" Title="" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div id="container" style="text-align:justify;">
          
1. Taraflar <br/>
İş bu sözleşmenin tarafları; <br/>
MARKA KAFA  DANIŞMANLIK HİZMETLERİ A.Ş. (Bundan böyle kısaca "MARKAKAFA" olarak anılacaktır) ile, www.markakafa.com portalına üye olurken iş bu sözleşmeye elektronik olarak onay veren "Üye"dir. <br/>
2. Tanımlar <br/>
İçerik: Sitede yayınlanan veya erişimi mümkün olan her türlü tasarım, logo, işaret, bilgi, dosya, resim, müzik rakam v.b görsel, yazınsal ve işitsel imgeleri; <br/>
Site: www.markakafa.com isimli alan adından ve bu alan adına bağlı alt alan adlarından oluşan web sitesi ve bu site ile bağlantılı olarak oluşturulan katma değerli hizmetlerin sunulduğu mecraları; <br/>
Hizmet(ler): Site içerisinde Kullanıcılar’a ve/veya Üyeler’e markakafa tarafından sunulan hizmetleri; <br/>
Kullanıcı(lar): Site’ye erişen gerçek ve tüzel kişileri; <br/>
Üye(ler): Site’ye Markakafa tarafından belirlenen yöntemlerle kayıt olan veMarkakafa tarafından üyeliği onaylanan, Site’de sunulan Hizmetler’den Markakafa Üyelik Sözleşmesi, Markkafa Kullanım Koşulları ve Markakafa Gizlilik Sözleşmesi’nde belirtilen koşullar dâhilinde yararlanan kişileri (üyelik, müşteri ve tasarımcıları da kapsar); <br/>
Müşteri(ler): Site üzerinde tasarım başlatan, Markakafa’ya tasarım için ödemede bulunan, Site’ye Markakafa tarafından belirlenen yöntemlerle kayıt olan ve Markakafa tarafından üyeliği onaylanan, Site’de sunulan Hizmetler’den Markakafa Üyelik Sözleşmesi, Markakafa Kullanım Koşulları ve Markakafa Gizlilik Sözleşmesi’nde belirtilen koşullar dâhilinde yararlanan gerçek ve/veya tüzel kişileri; <br/>
Tasarımcı(lar): Site üzerinde Müşteri(ler) tarafından başlatılan tasarım’lara tasarımları ile katılan, Site’ye Markakafa tarafından belirlenen yöntemlerle kayıt olan ve Markakafa tarafından üyeliği onaylanan, Site’de sunulan Hizmetler’den Markakafa Üyelik Sözleşmesi, Markakafa Kullanım Koşulları ve Markakafa Gizlilik Sözleşmesi’nde belirtilen koşullar dâhilinde yararlanan gerçek ve/veya tüzel kişileri; <br/>
Üyelik Bilgileri: üye’nin Markakafa Hizmetleri’ne erişimini sağlayan kullanıcı adı, parola ve/veya şifre v.b. gibi yalnızca üye tarafından bilinen bilgileri; <br/>
****Proje(ler): Açık proje, ekspres açık proje veya özel proje şeklinde gerçekleşebilen, Müşteri tarafından başlatılan, Tasarımcı’nın tasarımı ile katıldığı, Müşteri’nin son onayı vermesi ile sona eren süreci; <br/>
Tasarım: Tasarımcı’nın, Müşteri’nin başlattığı Proje kapsamında Müşteri’ye sunduğu eseri <br/>
ifade etmektedir. <br/>
"markakafa Üyelik Hesabı": Üye’nin site içerisinde sunulan hizmetlerden yararlanmak için gerekli olan iş ve işlemleri gerçekleştirdiği, proje başlatabildiği, tasarımları inceleyebildiği, yalnızca kendisinin belirlediği ve münhasıran kendisi tarafından kullanılacağını taahhüt ettiği "kullanıcı adı" ve "şifre" ile erişilebilen üyeye özel internet sayfası. <br/>
"Güvenli Elektronik Ticaret Sistemi": "müşteri ve tasarımcı arasında akdedilmiş olan satış ve devir akdinin ödeme koşullarına uygun olarak ifa edilmesini sağlamak amacıyla MARKAKAFA" tarafından sağlanan hizmet. Bu hizmet Markakafa’nın taraflar arasındaki alım satım ve devir ilişkisine taraf olduğu şeklinde yorumlanamaz. <br/>
"Güvenli Hesap": "Güvenli Elektronik Ticaret Sistemi"nde taraflarca gerçekleştirilen ödemelerin tutulduğu havuz hesabı. <br/>
3. Sözleşmenin Konusu ve Kapsamı <br/>
İşbu sözleşmenin konusu, müşteriler tarafından başlatılan projeler kapsamında tasarımcılar tarafından oluşturulan tasarımların müşteri ve tasarımcılar arasında alım satım ve devrine ilişkin koşulların belirlenmesi, tarafların hak ve yükümlülükleri ile site kullanım koşullarının belirlenmesi, bu kapsamda Markakafa hizmetlerinin ne suretle ifa edileceğidir. <br/>
Bu sözleşme markakafa.com üzerinde başlatılan projeler ve bu projelerle ilgili olarak oluşturulan tasarımlar, bu tasarımlar üzerindeki her türlü fikri ve sınai hak, proje, proje tasalağı üzerindeki hakların devri ile bu tasarımların satış ve devri ile ödeme koşulları ve site kullanım koşullarını kapsar. <br/>
4. Üyelik ve "Hizmet" Kullanımı Şartları <br/>
4.1. Kullanıcılar üye olmak istemeleri halinde site üzerinde ilgili yönledirmeleri takip ederek, üyelik formunda belirtilen bilgileri doldurmak, üyelik sözleşmesinde belirtilen şartları onaylayarak, gizlilik politikasında ve kullanım koşullarında belirtilen şartlara uyacağını taahhüt ederek üye olma hakkını kazanır. Üyelik işlemlerinin tamamlanması üyelik sözleşmesi, kullanım koşulları, gizlilik sözleşmesi ve bu sözleşmeler ekinde yer alan belgelerde belirtilen hak ve yükümlülüklerin kabul edildiği anlamına gelir. <br/>
4.2. Siteye üye olabilmek için reşit olmak ve fiil ehliyetine sahip olmak şarttır. Üyeliği dondurulan, üyelikten uzaklaştırılan veya üyeliği süresiz olarak yasaklanan kişilerin başka bir kullanıcı hesabıyla üye olmaları yasaktır. Bu yasağa aykırılık halinde oluşabilecek zararlardan Markakafa sorumlu tutulamaz, kişi kendisi sorumludur. <br/>
4.3.Markakafa, hiçbir gerekçe göstermeden bildirimsiz ve tazminatsız olarak üyeliği sona erdirme veya dondurma hakkına sahiptir. Üyeliğin sona erdirilmesi nedeniyle Markakafa’dan herhangi bir ad altında tazminat ve giderim talebinde bulunulamaz. <br/>
5. Hak ve Yükümlülükler <br/>
5.1. "Üye"nin Hak ve Yükümlülükleri <br/>
5.1.1. üye site üzerinde gerçekleştireceği her türlü işlem ve eylemde iş bu sözleşme koşullarına, kanuna, ahlaka ve adaba, temel ve ticari dürüstlük ilkelerine uyacağını kabul ve taahhüt eder. <br/>
5.1.2. Markakafa, yürürlükteki mevzuat uyarınca yetkili makamlardan usulüne uygun olarak talep gelmesi halinde üyenin’nın kendisinde bulunan bilgilerini ilgili yetkili makamlarla paylaşacaktır. Bu bilgiler üyeler arasında çıkan uyuşmazlıklarda diğer üyelerin yasal haklarını kullanabilmeleri amacıyla ve sadece bu kapsamla sınırlı olmak üzere uyuşmazlığa taraf olabilecek diğer üyelere iletilebilecektir. <br/>
5.1.3. Üye kayıt olurken veya sonraki aşamalarda edindiği veya kullandığı isim kullanıcı adı şifre vb. bilgilerin münferiden kendisi tarafından kullanılacağını bu bilgileri başkalarıyla paylaşmayacağını, bu bilgilerin doğru olduğunu kabul ve taahhüt eder. Bu bilgilerin doğru olmamasından, 3.kişilerin eline geçmesinden üye bizzat kendisi sorumludur. Aksi halde oluşabilecek zararlardan (diğer üyeler, 3.kişiler veya Markakafa’nın zararlarından) sorumludur. <br/>
5.1.4. Üyeler site üzerinde kendileri tarafından sağlanan bilgi, tasarım, eser, çizim, proje, grafik, işaret ses, görüntü, alan adı ve bunlarla sınırlı olmamak üzere her türlü içeriğin doğru ve hukuka uygun olduğunu, bu içerikler üzerindeki hakların kendilerine ait olduğunu, 3.kişilerin haklarını ihlal etmediğini, söz konusu bilgi ve içeriklerin site üzerinde yayınlanmasının veya bu içeriklerin yayınlanmasının ve teşhirinin yürürlükteki mevzuat doğrultusunda herhangi bir hukuka aykırılık veya hak ihlali yaratmadığını kabul ve taahhüt etmektedirler. Üyeler sözleşmeyi, proje ve tasarımdan kaynaklanan yükümlülükleri ile diğer yükümlülüklerini 3.kişiye devredemezler. <br/>
5.1.5. Markakafa, üyeler tarafındanMarkakafa’ya iletilen veya site üzerinden kendileri tarafından yüklenen, değiştirilen ve sağlanan bilgilerin ve içeriklerin doğruluğunu araştırma, bu bilgi ve içeriklerin güvenli, doğru ve hukuka uygun olduğunu taahhüt ve garanti etme ve bu içeriklerin internet üzerinden yayınlanmasının veya bu içeriklerle bağlantılı ürünlerin satışının ve teşhirinin hukuka aykırı bir durum oluşturmamasını sağlamakla yükümlü ve sorumlu olmadığı gibi söz konusu bilgi ve içeriklerin yanlış veya hatalı olmasından veya yayınlanmasından dolayı ortaya çıkacak hiçbir zarardan da sorumlu tutulamaz. <br/>
5.1.6. Üyelerin site üzerinde yaptığı her işlem ve eylemdeki hukuki ve cezai sorumluluk kendilerine aittir. Her kullanıcı sitede yer alan, 3.kişilerin veya Markakafa’nın haklarına tecavüz teşkil edecek nitelikte; tasarımları, projeleri, resimleri, metinleri, görsel ve işitsel imgeleri, video klipleri, dosyaları, veritabanları, katalogları ve listeleri çoğaltmayacağını, kopyalamayacağını, dağıtmayacağını, işlemeyeceğini, kullanmayacağını ve kullandırtmayacağını veya hak ihlaline sebep olacak biçimde bir işleme tabi tutmayacağını; yukarıda belirtilen nitelikteki hiçbir içeriği siteye yüklemeyeceğini; gerek bu eylemleri ile gerekse de başka yollarla Markakafa ile doğrudan ve/veya dolaylı olarak rekabete girmeyeceğini kabul ve taahhüt etmektedir. Üyelerin işbu sözleşme hükümlerine ve hukuka aykırı olarak gerçekleştirdikleri site üzerindeki faaliyetler nedeniyle üçüncü kişilerin uğradıkları veya uğrayabilecekleri zararlardan dolayı Markakafa doğrudan ve/veya dolaylı olarak hiçbir şekilde sorumlu tutulamaz. Site içerisinde yer alan içeriğin site dışında başka bir sitede veya herhangi bir şekilde kullanılması, kullanılmasının sağlanması, teşhir edilmesi ayrıca bir zarara veya hukuka aykırılığa sebep olma şartı aranmaksızın yasaktır. <br/>
5.1.7. Site içerisinde yer alan içerikten dolayı Markakafa’nın herhangi bir sorumluluğu bulunmamaktadır. Site içerisinde yer alan içerikten ve site üzerinde gerçekleşen eylemlerden kullanıcılar doğrudan sorumludurlar. <br/>
5.1.8. Üyeler site üzerinde gerçekleştirdikleri işlemlerle ilgili olarak, reklam veren, satıcı, vergi mükellefi veya benzeri sıfatlarla ilgili mevzuatın gerektirdiği önlem ve prosedürleri yerine getirmek zorunda olduklarını, bu önlem ve prosedürlerle ilgili markakafa’nın herhangi bir yetki ve sorumluluğu bulunmadığını, işbu madde içerisinde belirtilen kapsamda önlem ve prosedürlerin yerine getirilmemesi sonucunda doğacak tüm zararlardan dolayı diğer üyelerin, markakafa’nın ve/ veya üçüncü kişilerin uğradığı veya uğrayabileceği zararlardan sorumlu olacağını kabul, beyan ve taahhüt eder. <br/>
5.1.9. Üye sitede yayınlayacağı proje, tasarım veya her türlü içerikte karalama, kötüleme, iftira, tehdit, hakaret veya taciz etme gibi hukuka veya ahlaka aykırı hiçbir fiili gerçekleştirmeyeceğini, yüz kızartıcı, pornografik veya ahlaka aykırı içerikli metinlerin ve görsellere yer vermeyeceğini, yer vereceği tüm içeriğin; 3. kişilerin veya markakafa’nın rekabet, reklam, tüketici, fikri ve sınai mülkiyetten kaynaklanan hakları ve kişilik hakları başta olmak üzere ihlal oluşturmadığını/oluşturmayacağını kabul, beyan ve taahhüt eder. <br/>
5.1.10. Aşağıda belirtilen işlem ve eylemlerin gerçekleştirilmesi yasaktır. Bu eylem ve işlemlerin gerçekleştirilmesi halinde markakafa bir zarara uğrar veya 3. Kişinin uğradığı zararı gidermek zorunda kalırsa; bu eylem ve işlemleri gerçekleştirenler markakafa’nın zararını gidermekle yükümlüdürler. markakafa bu eylem ve işlemleri gerçekleştiren üyenin üyeliğine bildirimsiz olarak derhal son verebilir. <br/>
- Yanlış veya başkasının ismiyle üye olmak, yanlış veya yanıltıcı kişisel bilgiler, ikametgah adresi, e-posta adresi, ödeme ve hesap bilgileri vermek, <br/>
- Site’yi her türlü yasadışı veya hileli amaçla kullanmak; <br/>
- Başka birinin hesabını izinsiz kullanmak; <br/>
- Başka birinin yerine geçmek veya yanlış bir isimle projelere katılmak, proje başlatmak; <br/>
- Kişisel gizlilik ve yayın hakları da dâhil olmak üzere telif hakkı alınmış, ticari kanunla korunan veya 3. şâhısa ait içeriği sahibi olmadan veya izinsiz kullanmak; <br/>
- Herhangi bir projenin fiyatını manipüle etmek, ya da diğer kullanıcıların proje girişlerine müdahale etmek; <br/>
- Geçersiz veya izinsiz bir ödeme şekli kullanmak, hizmet bedelini, fatura ve ödeme süreçlerini manipüle etmeye çalışmak; <br/>
- Yorum ve puanlama sistemlerini site dışı amaçlar için kullanmak (sitedeki yorumları site dışında yayınlamak gibi); <br/>
- Zincir mektup veya istenmeyen e-posta (spam) yaymak; <br/>
- Virüs veya siteye zarar verici herhangi başka bir teknoloji yaymak, Kullanıcılar’a bu şekilde herhangi bir zarar vermek; <br/>
- Site içeriğini kopyalamak, değiştirmek veya izinsiz yaymak; Site’nin bütününü veya herhangi bir bölümünü bozmak, değiştirmek, tersine mühendislik yapmak amacıyla kullanmak; <br/>
- Kullanıcılar hakkında izinleri olmadan, e-posta adresleri dâhil, herhangi bir bilgi toplamak; <br/>
- Site’ye, makul olmayan veya sisteme orantısız derecede büyük yük getiren şekilde erişim sağlamaya çalışmak. <br/>
Üye siteden ayrıldığında sitede üye olduğu süre boyunca yaptığı işlemler (yüklenen projeler, tasarimlar, yorumlar) sitede kalmaya devam edebilir. Profil sayfası, kişisel bilgileri vb. içerik siteden silinebilir. <br/>
5.2. Markakafa’nın Hak ve Yükümlülükleri <br/>
5.2.1. Markakafa, işbu sözleşme ve eklerinde bahsi geçen hizmetleri, site içerisinde yer verilen açıklama ve işbu sözleşmede belirtilen koşullar dahilinde yerine getirmeyi, işbu sözleşme kapsamında belirtilen hizmetlerin sunulabilmesi için işbu sözleşmenin 4.maddesi ile belirlenen hükümler saklı kalmak şartıyla gerekli olan teknolojik altyapıyı tesis etmeyi ve işletmeyi kabul, beyan ve taahhüt eder. <br/>
5.2.2. Markakafa, siteye yüklenen bilgileri ve içerikleri hiçbir bildirim yapmaksızın ve gerekçe göstermeksizin çıkarma, silme, erişime kapatma, değiştirebilme hakkına sahiptir. Markakafa sitede yer alan içeriğin değiştirilmesi veya düzeltilmesi konusunda üyelere bildirimde bulunabilir. Üyeler tarafından da içeriğin değiştirilmesi talebi Markakafa yöneltilebilir. markakafa bu içeriği değiştirme konusunda takdir hakkını gerekçe göstermeksizin kullanabilir. <br/>
Üyeler tarafından yerine getirilmesi gereken değişikliklerin yerine getirilmemesi nedeniyle oluşacak zararlardan üyeler sorumludur. markakafa’dan bu nedenle herhangi bir zarar ve giderim talebinde bulunulamaz. <br/>
5.2.3. Üyeler, site üzerinde markakafa prensip ve sözleşme koşullarına veya hukuka aykırı olmayan başka içeriklere link verebilirler. Ancak bu halde markakafa’nın herhangi bir sorumluluğu yoktur. <br/>
5.2.4. markakafa sitede yer alan içeriği dilediği biçimde tasnif edebilir, reklam, tanıtım veya başka amaçlarla kullanabilir. Üyeler bu içerik üzerinde fikri, sınai, mali, manevi veya başka ad altında hak sahibi oldukları gerekçesiyle markakafanın yetkisine müdahale edemezler, hak ihlali olduğu iddiasında bulunamazlar, tazminat veya giderim talep edemezler. 3. Kişilere karşı da markakafa’nın herhangi bir sorumluluğu yoktur. 3. Kişilerin hak sahipliği nedeniyle talepte bulunmaları halinde, bu talepler doğrudan bu duruma sebep olan üye tarafından karşılanacaktır. markakafanın ayrıca zarar giderim talep etme hakkı saklıdır. <br/>
5.2.5. Üyeler, site üzerindeki yazışmalarının, kullandıkları ve yükledikleri içeriklerin hukuka, ahlaka, adaba ve sözleşme koşullarına aykırı olmamasını taahhüt ederler. Belirtilen içerik markakafa tarafından kontrol altına alınabilir, denetlenebilir, kayıt altına alınabilir ve kullanılabilir. <br/>
5.2.6. Markakafa’nın üyeler tarafından yüklenen içeriği (proje, tasarım, eser, logo, işaret, isim, görseller ve bunlarla sınırlı olmamak üzere her türlü bilgi) hiçbir bildirim yapmaksızın tazminatsız olarak derhal kaldırabilir ve/veya üyelik sözleşmesini feshedebilir. Bu içerikleri yükleyenler veya bu içeriklerden yararlananlar, bu içerikler nedeniyle proje geliştirenler veya tasarım geliştirenler, herhangi bir nedenle harcama yapanlar, herhangi bir isim altında markakafa’dan talepte bulunamayacaklarını kabul ve taahhüt ederler. Üyeler, proje başlatma, tasarım geliştirme veya satın alma süreçlerinde bu ihtimallerin olduğunu ve bu nedenle fikri ve sınai hak koruması da dahil olmak üzere markakafa’nın herhangi bir taahhüdünün olmadığını ve markakafa’dan herhangi bir talepte bulunamayacaklarını gayri kabili rücu kabul ve taahhüt ederler. <br/>
5.2.7. Kullanım bedeli <br/>
- markakafa.com üyeliği için her hangi bir ücret talep edilmez. <br/>
- Proje sahibi üye, markakafa’ya aldığı hizmet karşılığında bir hizmet bedeli öder. Bu bedel şu an için yarışmada belirtilen ödül bedelinin %25’idir. Verilebilecek ek hizmetlerin içerikleri ve bedelleri ödeme sayfasında belirtilmiştir ve hizmet bedeline dahil değildir. <br/>
- Proje sahibi, yarışmaya en az 10 adet tasarım katılması halinde bu tasarımlardan birisini seçmek zorundadır. Proje sahibinin seçim yapmaması halinde seçim hakkı markakafa tarafından kullanılır. Bu halde bedel ödemekten kaçınamaz. Özel projelerde tasarım sayısına bakılmaksızın proje sahibi ödeme yapmakla yükümlüdür. <br/>
<%--- Tasarımcı, kazandığı ödül bedelinin %25’unu markakafa’ya hizmet bedeli olarak vermeyi kabul eder. <br/>--%>
5.2.8.Vergi <br/>
Belirlenen yarışma ödülü bedeline, MARKAKAFA hizmet bedeli ve KDV dahil olmayacaktır. <br/>
5.2.8.1. Belirlenen yarışma ödülü bedeline, markakafa hizmet bedeli ve KDV dâhil değildir.<br/>
5.2.8.2. Tasarımcı kazandığı birincilik ödül bedeli nettir. Ödülün vergisi/stopajı müşteri tarafına aittir. <br/>
Tasarımcının müşteriye fatura kesmesi durumunda ödül bedeli+KDV olarak kesilir ve KDV tutarı müşteri tarafından tasarımcının hesabına yatırılır. Tasarımcının gider pusulası imzalaması durumunda ödül bedelinden doğan stopaj bedelini müşteri yüklenir.<br/>
5.2.8.3. Tasarımcı ve müşteri mali mevzuattan kaynaklanan yükümlülüklerini yerine getirmekle mükelleftir. Bu konuda markakafa’nin taraflara veya 3. Kişilere karşı herhangi bir sorumluluğu yoktur.<br/>
5.2.9. Markakafa Hizmetleri ve Kullanım Koşulları <br/>
markakafa işbu sözleşme koşullarıyla belirlenen hizmetleri üyelere sağlayacaktır. <br/>
Üyelerin hukuken üzerinde tasarrufta bulunabilecekleri tasarımlar ve sözleşme kapsamında yer alabilecek diğer unsurların belli bir bedel karşılığında ilgili kişiler tarafından satın alınması, kiralanması veya takasa konu yapılması gibi hukuki işlemlere konu olabilecek sisteme site üzerinde yer verilir. Site üzerinde üyeler, birbiri arasında işbu sözleşmede belirtilen "Güvenli Elektronik Ticaret Sistemi"ni kullanarak, başlatılan projelerde, sergilenen ilanlarda belirtilen koşullar çerçevesinde, üzerinde tasarruf yetkilerinin olduğu ürünlerin satışının yapılması ve ödemenin tahsil edilmesi amacıyla işlem gerçekleştirebilirler. markakafa.com üzerinde bu işlemlerin gerçekleştirilmesi, markakafa’nın bu işlemlerin tarafı olduğu şeklinde yorumlanamaz. Hukuka aykırı işlem ve eylemler nedeniyle tüm sorumluluk bu eylem ve işlemleri gerçekleştiren üyelere aittir. Üyeler, markakafa’nın doğrudan ve/veya dolaylı olarak sorumluluğu tutulamayacağını kabul ve taahhüt ederler. <br/>
6.1. markakafa İlan ve Reklam Hizmetleri <br/>
6.1.1. Üye, “markakafa üyelik hesabı” üzerinden, markakafa tarafından belirlenen "Proje Turleri"ne göre üyelik hesabı içerisindeki ara yüzleri kullanarak ihtiyacı olan tasarım hizmeti ile ilgili projeyi yaratacak ve markakafa veritabanı’na yükleyecektir. <br/>
6.1.2. markakafa, üye tarafından "markakafa Üye Hesabı" üzerinden yapılan seçimler doğrultusunda "Proje başlatma" verilerine uygun olarak "Üye" tarafından oluşturulan projeyi değerlendirmeye alacak; bahsi geçen projelerin, "Proje baslatma" verilerinde belirtilen şekilde sitede yayınlanmasını kabul veya red edecektir. markakafa, üye tarafından "Proje baslatma" verilerine uygun olarak oluşturulan projenin yayınlanması talebinin değerlendirmesine yönelik kriterleri, koşulları ve süreleri serbestçe tayin ve tespit ederek bu kriter ve koşulları sitenin "Proje baslat" imlerine ilişkin kısmında yayınlayacaktır. <br/>
6.1.3. . markakafa, Üye’nin açık projeleri veya ekspres açık projelerinin ve tasarımlarının başka internet sitelerinde ve arama motorlarında görüntülenebilmesi için üçüncü kişilerle anlaşma yapabilir. Arama motorlarında gizleme seçeneğinin seçilmesi halinde üçüncü kişilerle bu konuda anlaşma yapılamaz. Özel Projeler arama motorlarında otomatik olarak gizlenir. Üye, bu konuda markakafa’nın yetkili olduğunu kabul etmektedir. <br/>
6.1.4. Üye, “Markakafa Üyelik Hesabı" üzerinden başta "Proje Baslatma"ya ve “Tasarim Yukleme”ye ilişkin seçimleri olmak üzere "Markakafa Üyelik Hesabı" içerisinde gerçekleştirdiği seçimlere ilişkin yapmış olduğu her türlü işlemin ve talebin kendisini gayrikabili rücu olarak bağladığını kabul, beyan ve taahhüt eder. <br/>
6.1.5. Üye, "Markakafa Üyelik Hesabı" üzerinden yaptığı her türlü iş ve işlemin sorumluluğunun kendisine ait olduğunu; burada gerçekleştirilen iş ve işlemleri kendisinin gerçekleştirmediği yolunda herhangi bir def’i ve/veya itiraz ileri süremeyeceğini ve/veya bu def’i veya itiraza dayanarak yükümlülüklerini yerine getirmekten kaçınmayacağını kabul, beyan ve taahhüt eder. <br/>
6.1.6. Üye, başlatmış olduğu projede, site tarafından belirtilen koşullar çerçevesinde gerekli olan iş ve işlemleri eksiksiz olarak yerine getirmeyi ve başlatmış olduğu projenin bedelini sitede belirtildiği şekilde markakafa havuz hesabına yatırmayı kabul, beyan ve taahhüt eder. <br/>
6.1.7. Proje Başlatmak <br/>
markakafa’da proje başlatan üye, alacağı tasarım hizmeti için bir bedel ödeyeceğini kabul eder. Bir kaç alternatif arasından seçtiği işin ait olduğu tasarımcıya, proje başında belirlenen ödül bedeli verilir. Üye, site tarafından belirlenen minimum bedellerin altında bir bedel belirleyemez. Üye, tasarımcıya ödenecek ödül bedeline ek olarak siteye %25 komisyon ve ek hizmetler için sitede belirtilen bedelleri ödemeyi kabul eder. Ödeme, yarışma başlangıcında alınır ve yarışma boyunca tüm bedel (ödül + markakafa hizmet komisyonu + ek hizmetlerin bedeli ) markakafa tarafından havuz hesabında muhafaza edilir. Yarışma sonunda kazanan tasarımcıya ödül bedeli kadar ödeme markakafa havuz hesabından yapılır. <br/>
6.1.8. Kazanan Tasarımı Seçmek <br/>
Müşteri, kazanan Tasarım’ı Proje süresinin veya belirlenmişse ek sürenin bitiminden itibaren 5 gün içinde seçmek zorundadır. Seçilen Tasarım, Müşteri tarafından satın alınmış sayılır. Kazanan Tasarımcı tüm gerekli dokümanları doğru ve kusursuz bir şekilde Müşteri’ye teslim etmekle yükümlüdür. Müşteri seçimini 5 gün içinde yapmazsa markakafa’nın kendisi yerine kazananı belirleyebileceğini kabul eder. Kazanan tasarım belirlendikten sonra proje 10 gün içinde sonuçlandırılmalıdır. <br/>
Musteri secimini yaptiktan sonra 10 gun icinde varsa tasarimcidan kazanan eser ile ilgili degisikliklerini talep eder. Tasarimci 48 saat icinde bu değişiklik taleplerini yerine getirmeli veya taleplere ilişkin görüşünü belirtmelidir. Bu aşamada karşılıklı mutabakat ve iyiniyet esasına dayalı olarak görüşmeler sonlandırılır. Bu görüşmeler ve anlaşmazlıklar nedeniyle markakafa’nın herhangi bir sorumluluğu yoktur. Müşteri tasarımın son halini onayladıktan sonra, tasarımcı hak devri ve tasarıma ilişkin tüm ayrıntıların yer aldığı dosyayı müşteriye teslim eder. Dosyanın müşteriye ulaşması ve hak devir sözleşmesinin imzalanıp markakafa’ya ulaştırıldıktan sonra 2 iş günü içinde tasarımcıya ödeme yapılır. Müşterinin ödeme yapılmasından önce markakafa’ya herhangi bir bildirimde bulunmaması ödemeye onay verdiği anlamına gelir. Müşterinin, ödeme yapılmadan önce ödemeye ilişkin muhalefetini markakafa’ya ulaştırması halinde, tasarımcıya ödeme yapılması taraflar arasındaki uzlaşmazlığın sonlandırılmasına kadar bekletilebilir. Tüm bu süreçler yarışma süresi sona erdikten sonra “Proje Sonlandır” bölümü üzerinden gerçekleştirilir. <br/>
Tasarımın müşteri adına seçilmiş sayılması halinde markakafa’nın değişiklik talep etme yükümlülüğü yoktur. Taraflar sürecin ilerleyişi ve işleyişi nedeniyle aksaklıklar çıkabileceğini, tüm bu süreçlerin uygulanması ile ilgili olarak ortaya çıkabilecek zararlardan markakafa’nın herhangi bir sorumluluğu olmadığını kabul ve taahhüt ederler. <br/>
6.1.15. Garanti <br/>
Proje süresi sonunda 10’dan az tasarım oluşturulması halinde, eğer üye hiçbir tasarımı ödüle layık görmezse veya yarışma süresini uzatmak istemezse, markakafa, havuz hesabına yatan paranın iadesini garanti eder.10 tasarımın oluşturulması halinde, proje sahibi proje bedelini ödemek zorundadır. <br/>
6.1.16. Projeye Katılmak <br/>
Tasarımcı, markakafa.com’a yüklediği içerikten sorumludur. Bu siteye yüklediği tüm içeriğin kendisine ait olduğunu, kullanım, mülkiyet ve tasarruf haklarının kendisinde olduğunu garanti eder. Tasarımcı, siteye yüklediği tasarımların orijinal olduğunu ve başka bir tasarımdan kopyalanmadığını garanti eder. Tasarımda 3. Kişilere ait olan ve haklarının devralınmasını gerektiren stok görüntü, müzik, video vb. unsurların bulunması halinde bu unsurların hak devir masrafları müşteriye aittir. Ancak tasarımcının bu unsurlar üzerinde kendisinin hak sahibi olmadığını ve hak devrinin gerektiğini, en geç proje kabul edilmeden önce müşteriye bildirmesi gerekir. <br/>
Tasarımcı, yarışmada birinci seçildiği taktirde yüklediği işi eksiksiz teslim etmekle yükümlüdür. <br/>
6.1.17. Telif Hakları <br/>
Siteye yüklenen tasarımların telif hakkı tasarımcıya aittir. Tasarımcı bu hakların kendisine ait olduğunu, 3.kişilerin ve markakafa’nın haklarını ihlal etmediğini kabul ve taahhüt eder. Tasarımcı, yarışmayı kazanan tasarım üzerindeki tüm haklarını proje sahibine transfer etmeyi kabul beyan ve taahhüt eder. Bunun karşılığında tasarımcı ödül bedelini alır. Birinci seçilmeyen tasarımlar üzerindeki haklar onları tasarlayana aittir. <br/>
6.1.18. Tasarımı Geri Çekmek <br/>
Tasarımcı yarışma açık kaldığı sürece tasarımını geri çekebilir, projenin seçilme süresinin dolmasından sonra tasarın tasarımcı tarafından geri çekilemez. <br/>
6.1.19.Kazanan tasarımın belirlenmesi <br/>
Kazanan tasarım belirlendiğinde tasarım sahibi tasarımcı, projeye ait tüm içeriği eksiksiz bir şekilde teslim etmekle yükümlüdür. Telif hakları tasarımcıdan proje sahibine devredilir. <br/>
7.Sorumluluk <br/>
Kullanıcı markakafa’nın üyeler arasındaki işlemlerin gerçekleştirilebilmesi için bir internet sitesi sunduğunu kabul eder ve üyeler arasındaki işlemlerden dolayı markafanın sorumlu tutulamayacağını kabul ve taahhüt eder. markakafa yüklenen projelerin veya işlerin gerçekliklerini, kalitelerini, hak sahipliğini takip veya kontrol etmez. Yüklenen içerikler tamamen üyelerin sorumluluğundadır. Sorumluluğun belirlenmesinde madde 5 hükümleri taraflar için bağlayıcıdır. <br/>
8. Ek Hizmetler <br/>
Üyeler, sitede belirtilen temel hizmetler dışında ek bir ücretle ek bir hizmetin sunulması halinde bu ek hizmetlerden belirtilen ücreti ödeyerek yararlanabilirler. <br/>
9. Sözleşme Değişiklikleri <br/>
markakafa, işbu sözleşmeyi tek taraflı olarak uygun göreceği bir zamanda sitede ilan ederek değiştirebilir. İşbu sözleşmenin değişen hükümleri, ilan edildikleri tarihte geçerlilik kazanacak, geri kalan hükümler aynen yürürlükte kalarak hüküm ve sonuçlarını doğurmaya devam edecektir. <br/>
10. Mücbir Sebepler <br/>
Mücbir sebep sayılan tüm durumlarda,markakafa işbu sözleşme ile belirlenen edimlerinden herhangi birini geç veya eksik ifa etme veya ifa etmeme nedeniyle yükümlü tutulamaz. Bu ve bunun gibi durumlar, markakafa için, gecikme, eksik ifa etme veya ifa etmeme veya temerrüt addedilmeyecek veya bu durumlar için markakafa’dan herhangi bir nam altında tazminat talep edilemeyecektir. <br/>
Mücbir sebep; doğal afet, isyan, savaş, grev, iletişim sorunları, altyapı ve internet arızaları, sisteme ilişkin iyileştirme veya yenileştirme çalışmaları ve bu sebeple meydana gelebilecek arızalar, elektrik kesintisi ve kötü hava koşulları da dâhil ve fakat bunlarla sınırlı olmamak kaydıyla ilgili tarafın makul kontrolü haricinde gerçekleşen olaylar olarak yorumlanacaktır. <br/>
11markakafa Kayıtlarının Geçerliliği <br/>
Üye, işbu sözleşmeden doğabilecek ihtilaflarda markakafa’nın kendi veritabanında, sunucularında tuttuğu elektronik ve sistem kayıtlarının, ticari kayıtlarının, defter ve diğer kayıtlarının, mikrofilm, mikrofiş ve bilgisayar kayıtlarının muteber bağlayıcı, kesin ve münhasır delil teşkil edeceğini ve bu maddenin HUMK 287. Madde anlamında kesin delil sözleşmesi niteliğinde olduğunu kabul, beyan ve taahhüt eder. <br/>
12. Uygulanacak Hukuk ve Yetki <br/>
İşbu sözleşmenin uygulanmasında, yorumlanmasında ve işbu sözleşme dâhilinde doğan hukuki ilişkilerin yönetiminde yabancılık unsuru bulunması durumunda da Türk Hukuku uygulanacaktır. İşbu sözleşmeden doğan veya doğabilecek her türlü ihtilafın hallinde İstanbul Mahkemeleri ve İcra Daireleri yetkilidir. <br/>
13. Bildirim <br/>
Üyeler ile kayıt olurken bildirdikleri email vasıtasıyla veya sitede yer alan genel bilgilendirme aracılığıyla iletişim kurulacaktır. Email ile yapılan iletişim yazılı iletişimin yerini tutar. Email adresini güncel tutmak ve siteyi bilgilendirmeler için düzenli kontrol etmek üye’nin sorumluluğundadır. Proje sonunda belirtilen geri dönüş surelerine markanın veya tasarımcının uymaması durumunda doğabilecek zararlardan üye kendisi sorumludur. <br/>
14. Yürürlülük <br/>
İşbu sözleşme ve sözleşmeyle atıfta bulunulan ve sözleşmenin ayrılmaz bir parçası olan belgelerden ve eklerden (Hepsi birlikte “sözleşme”) üyenin elektronik olarak onay vermesi ile bu tarihte karşılıklı olarak kabul edilerek yürürlüğe girmiştir.<br/>


        </div>

</asp:Content>
